format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$python\
$fill\
$jobs $cmd_duration $time\
$line_break\
$character"""
command_timeout = 5000
add_newline = false

[fill]
symbol = " "

[python]
format = 'via [${symbol}(\($virtualenv\) )]($style)'

[git_branch]
format = "[$symbol$branch]($style) "

[aws]
disabled = true

[character]
format = "λ "

[jobs]
symbol = "༼ つ ◕_◕ ༽つ"
format = "[$symbol]($style)"
style = "bold red"
number_threshold = 1

[cmd_duration]
format = "[$duration]($style)"

[git_status]
style = "red"

[time]
disabled = false
style = "bold white"
format = "[$time]($style) "
