#! /bin/bash

source ~/.config/Juliet/_util.bash

setup_git() {
  [[ ! -f ~/.gitconfig__local ]] && cp ~/.config/Juliet/.gitconfig__local ~
}

setup_dependencies() {
  if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  if ! command -v gum &> /dev/null; then
    brew install gum
  fi

  if [[ ("$1" != "-n" && "$1" != "--no") && ("$1" == "-y" || "$1" == "--yes" || ($(gum confirm "Would you like to brew bundle?") || $? == 0)) ]] ; then
    brew bundle --file ~/.config/Juliet/Brewfile
  fi

  if ! command -v cargo &> /dev/null; then
    rustup-init
  fi

  log "Symlinking dotfiles..."
  stow --stow --target=$HOME --dir=$HOME/.config/Juliet/symlinked home
  stow --stow --target=$HOME/.config --dir=$HOME/.config/Juliet/symlinked config
}

setup_fzf() {
  if ! command -v fzf &> /dev/null; then
    /opt/homebrew/opt/fzf/install
  fi
}

setup_fish() {
  mkdir -p ~/.config/fish

  if [[ ("$1" != "-n" && "$1" != "--no" ) && ("$1" == "-y" || "$1" == "--yes" || ($(gum confirm "Would you like to do a full fish install?") || $? == 0)) ]]; then
    sudo bash -c "echo '/opt/homebrew/bin/fish' >> /etc/shells"
    chsh -s /opt/homebrew/bin/fish `whoami`
  fi
}

setup_gpg() {
  if [[ ! -d $HOME/.gnupg ]]; then
    mkdir ~/.gnupg
    touch ~/.gnupg/gpg-agent.conf
    echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
  fi
}

setup_rust() {
  if ! command -v stylua &> /dev/null; then
    cargo install stylua
  fi

  if ! command -v silicon &> /dev/null; then
    cargo install silicon
  fi
}

setup_kitty() {
  if ! command -v kitty &> /dev/null; then
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  fi
  [[ ! -f /usr/local/bin/kitty ]] && sudo ln -s /Applications/kitty.app/Contents/MacOS/kitty /usr/local/bin

  [[ ! -f $HOME/Library/Fonts/3270-nerdfont-complete.ttf ]] && cp $HOME/.config/Juliet/etc/fonts/3270-nerdfont-complete.ttf $HOME/Library/Fonts/
}

setup_other() {
  touch ~/.hushlogin
}

rlog "Setting up git..."
setup_git
rlog "Setting up external dependencies..."
setup_dependencies $1
log "Installing fzf..."
setup_fzf
log "Installing fish..."
setup_fish $1
log "Installing gpg..."
setup_gpg
log "Installing rust dependencies..."
setup_rust
log "Installing kitty..."
setup_kitty

log "Silencing logins..."
setup_other

log "Done!"
