#! /bin/bash

setup_git() {
  [[ ! -f ~/.gitconfig ]] && ln -sfv ~/.vim/.gitconfig ~/
}

setup_dependencies() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew bundle
}

setup_fzf() {
  /usr/local/opt/fzf/install
}

setup_vim() {
  [[ ! -f ~/.vimrc ]] && ln -sfv ~/.vim/.vimrc ~/
  [[ ! -d ~/.config/nvim ]] && ln -sfv ~/.vim ~/.config/nvim
}

setup_fish() {
  curl -fsSL https://starship.rs/install.sh | bash
  ln -sfv ~/.vim/fish/config.fish ~/.config/fish/
  mkdir -p ~/.config/fish/functions
  ln -sfv ~/.vim/fish/fish_user_key_bindings.fish ~/.config/fish/functions
  ln -sfv ~/.vim/starship.toml ~/.config/
}

setup_gpg() {
  echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
}

setup_git
# setup_dependencies
# setup_fzf
setup_vim
setup_fish
# setup_gpg
