command_timeout = 5000
add_newline = false

[package]
disabled = true

[nodejs]
disabled = true

[aws]
disabled = true

[character]
format = "λ "

[jobs]
symbol = "༼ つ ◕_◕ ༽つ |"

[git_status]
style = "red"
