theme = "bamboo"

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
C-c = "no_op"

[keys.select]
C-c = "collapse_selection"

[keys.insert]
C-c = "normal_mode"

[editor]
bufferline = "always"
